Repository ngtrgiabaoB2012063/Foodysor, pull requests merged in 2022-11, with the labels that each got.

#32 #8 - fix overflow image
  db/blogs.js
  pages/home.html
Labels: bug

#38 add about page
  pages/about.html
Labels: page

#58 #54 - add reponsive dangKy dangNhap dieuKhoan thanhToan
  pages/dangKy.html
  pages/dangNhap.html
  pages/dieuKhoan.html
  pages/thanhToan.html
  public/css/output.css
Labels: feature

#62 #61 - fix ui homepage move phone image to left
  db/khuyenmai.js
  pages/dangNhap.html
  pages/home.html
  pages/khuyenMai.html
  public/css/output.css
  styles/responsive/mobile/khuyenmai/main.css
Labels: bug
